### ISSUE TITLE
Seems not support JSON schema

### ISSUE THREAD

**Issue by libook** [d-band/koa-mapper#15]
```javascript
mapper.post("/", {
    "body": {"$schema":"https://example.com#mySchema.json"},
});
```
```bash
TypeError: Cannot read property 'trim' of undefined
    at transformType (./node_modules/koa-mapper/lib/utils.js:176:15)
    at ./node_modules/koa-mapper/lib/utils.js:214:23
    at Array.forEach (<anonymous>)
    at propsToSchema (./node_modules/koa-mapper/lib/utils.js:209:24)
    at Layer.setBodyValidate (./node_modules/koa-mapper/lib/layer.js:204:48)
    at Layer.setBodyParser (./node_modules/koa-mapper/lib/layer.js:193:12)
    at new Layer (./node_modules/koa-mapper/lib/layer.js:44:10)
    at Mapper.register (./node_modules/koa-mapper/lib/index.js:241:19)
    at Mapper.post (./node_modules/koa-mapper/lib/index.js:99:12)
    at Object.<anonymous> (./routes/index.js:66:8)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (./routes/index.js:40:22)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
```

I might misunderstand this.
So koa-mapper is using proprietary schema format. And then transform it to JSON schema.

🤔 Am I right?

I love your idea about "required" keyword.
But what do you think about using a common specification?

**Comment by helloyou2012** [comment]
This is a bug and it has been fixed at `v0.1.2`. Use `$ref` like this:
```
const mapper = new Mapper();

mapper.post('/pets', {
  body: 'Pet'
}, ctx => {
  ctx.body = ctx.request.body;
});

mapper.define('Pet', null, {
  $ref: 'https://example.com#mySchema.json'
});

app.use(mapper.routes());
app.use(mapper.allowedMethods());
```

**Comment by helloyou2012** [comment]
`body: 'Pet'` transform to:
```
body: { $ref: 'Pet' }
```

`body: { id: { type: 'number' } }` transform to:
```
body: {
  type: 'object',
  properties: {
    id: { type: 'number' }
  }
}
```

**Comment by libook** [comment]
The error is gone. But the request is hanged up. No response before timeout. 😂

**Comment by helloyou2012** [comment]
fixed at `v0.2.0`

**Comment by libook** [comment]
Thanks for your work.

But problem is still. ¯\_(ツ)_/¯
I'll take time to deeply check it out.

**Comment by helloyou2012** [comment]
@libook do you have provide a minimal bug-demonstrating test case. Like this: https://github.com/d-band/koa-mapper/blob/master/examples/simple.js
